# Generated by Django 5.0 on 2023-12-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billSundryName', models.CharField(max_length=1000)),
                ('Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('InvoiceNumber', models.CharField(max_length=1000)),
                ('CustomerName', models.CharField(max_length=1000)),
                ('BillingAddress', models.CharField(max_length=1000)),
                ('ShippingAddress', models.CharField(max_length=1000)),
                ('GSTIN', models.CharField(max_length=1000)),
                ('TotalAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=1000)),
                ('Quantity', models.FloatField()),
                ('Price', models.FloatField()),
                ('Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice_bill_sundry', models.ManyToManyField(to='invoice.invoicebillsundry')),
                ('invoice_headers', models.ManyToManyField(to='invoice.invoiceheader')),
                ('invoice_items', models.ManyToManyField(to='invoice.invoiceitems')),
            ],
        ),
    ]
